kind = "web"
previewPath = "/"
title = "Smart Park & Ride"
version = "1.0.0"
id = "artifacts/park-and-ride"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18372

[services.development]
run = "pnpm --filter @workspace/park-and-ride run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/park-and-ride", "run", "build" ]
publicDir = "artifacts/park-and-ride/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18372"
BASE_PATH = "/"
